name: GCPClan
main: instantlyta\fcaclan\FCAClan
version: 1.1
api: [4.0.0]
author: InstantlyTa
description: Chúng ta hãy có một số gia tộc nào!
website: http://fcape.vn
commands:
  clan:
    description: Lệnh Clan
    aliases: ["c"]
  clanchat:
    description: Trò Chuyện Clan
    aliases: ["cchat", "cc"]